name: VaultX

options:
  bundleIdPrefix: com.surrel14
  deploymentTarget:
    iOS: "16.0"

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1,2"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Manual

targets:

  VaultX:
    type: application
    platform: iOS

    sources:
      - path: VaultX

    resources:
      - path: VaultX/Resources

    entitlements:
      path: VaultX/VaultX.entitlements

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.surrel14.VaultX
        PRODUCT_NAME: VaultX
        EXECUTABLE_NAME: VaultX
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        INFOPLIST_FILE: VaultX/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        SKIP_INSTALL: NO

    dependencies:
      - target: VaultXFileProvider

  VaultXFileProvider:
    type: app-extension
    platform: iOS

    sources:
      - path: VaultXFileProvider

    entitlements:
      path: VaultXFileProvider/VaultXFileProvider.entitlements

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.surrel14.VaultX.FileProvider
        PRODUCT_NAME: VaultXFileProvider
        EXECUTABLE_NAME: VaultXFileProvider
        INFOPLIST_FILE: VaultXFileProvider/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        SKIP_INSTALL: NO

  VaultXTests:
    type: bundle.unit-test
    platform: iOS

    sources:
      - path: VaultXTests

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.surrel14.VaultXTests
        GENERATE_INFOPLIST_FILE: YES

    dependencies:
      - target: VaultX
